name: hello-world-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Hello world
        run: echo "Hello Github Action"
      - name: Get current date
        id: date
        run: echo "::$GITHUB_OUTPUT name=date::$(date +'%Y-%m-%d')"
      - name: Print current Git branch
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Current Git Branch: $BRANCH_NAME"